name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: UPSC-Question-Analyzer.exe
            asset_name: UPSC-Analyzer-Windows
            asset_extension: zip
          - os: macos-latest
            artifact_name: UPSC Question Analyzer.app
            asset_name: UPSC-Analyzer-macOS
            asset_extension: zip

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./upsc-question-analyzer
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      working-directory: ./upsc-question-analyzer
      run: |
        pyinstaller upsc-analyzer.spec --noconfirm --clean

    - name: Prepare Windows artifact
      if: matrix.os == 'windows-latest'
      working-directory: ./upsc-question-analyzer
      run: |
        Compress-Archive -Path "dist\${{ matrix.artifact_name }}" -DestinationPath "..\${{ matrix.asset_name }}.${{ matrix.asset_extension }}"
      shell: powershell

    - name: Prepare macOS artifact
      if: matrix.os == 'macos-latest'
      working-directory: ./upsc-question-analyzer
      run: |
        cd dist
        zip -r "../../${{ matrix.asset_name }}.${{ matrix.asset_extension }}" "${{ matrix.artifact_name }}"


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}.${{ matrix.asset_extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -la artifacts/*/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: UPSC Question Analyzer ${{ github.ref_name }}
        body: |
          ## UPSC Question Quality Analyzer ${{ github.ref_name }}
          
          ### 🚀 What's New
          - Enhanced Ollama connection detection
          - Automatic setup instructions
          - Improved user experience
          
          ### 📥 Installation
          
          1. **Download** the appropriate file for your system below
          2. **Install Ollama** from https://ollama.com
          3. **Download the AI model**: `ollama pull gemma2:9b`
          4. **Run** the application
          
          ### 📦 Downloads
          - **Windows**: `UPSC-Analyzer-Windows.zip`
          - **macOS**: `UPSC-Analyzer-macOS.zip`
          
          ### 📋 System Requirements
          - RAM: 16GB recommended
          - Storage: 10GB free space
          - Ollama installed and running
          
          See [README_OLLAMA_SETUP.md](https://github.com/${{ github.repository }}/blob/main/upsc-question-analyzer/README_OLLAMA_SETUP.md) for detailed instructions.
        draft: false
        prerelease: false
        files: |
          artifacts/UPSC-Analyzer-Windows/UPSC-Analyzer-Windows.zip
          artifacts/UPSC-Analyzer-macOS/UPSC-Analyzer-macOS.zip